const fs = require("fs");
const path = require("path");

// Determine if we're in project-setup or theme-setup mode
const rootHugoToml = path.join(__dirname, "../hugo.toml");
const exampleSiteHugoToml = path.join(__dirname, "../exampleSite/hugo.toml");

let hugoTomlPath, themePath, isThemeSetup, outputPath;

// Check which mode we're in
if (fs.existsSync(exampleSiteHugoToml)) {
  // Theme setup mode - exampleSite structure exists
  hugoTomlPath = exampleSiteHugoToml;
  themePath = path.join(__dirname, "../exampleSite/data/theme.json");
  outputPath = path.join(__dirname, "../assets/css/theme-generated.css");
  isThemeSetup = true;
} else if (fs.existsSync(rootHugoToml)) {
  // Project setup mode - hugo.toml at root
  hugoTomlPath = rootHugoToml;
  themePath = path.join(__dirname, "../data/theme.json");
  
  // Read hugo.toml to get theme name for project setup
  const hugoTomlContent = fs.readFileSync(hugoTomlPath, "utf8");
  const themeNameMatch = hugoTomlContent.match(/^theme\s*=\s*["'\[]?"?([^"'\]]+)"?[\]"]?/m);
  const themeName = themeNameMatch ? themeNameMatch[1] : "hugoplate";
  
  // In project setup, CSS goes to themes/{themeName}/assets/css/
  outputPath = path.join(
    __dirname,
    `../themes/${themeName}/assets/css/theme-generated.css`,
  );
  isThemeSetup = false;
}

// Read theme.json
const themeConfig = JSON.parse(fs.readFileSync(themePath, "utf8"));

// Helper to convert color name from snake_case to kebab-case
const toKebab = (str) => str.replace(/_/g, "-");

// Helper to extract a clean font name
const findFont = (fontStr) =>
  fontStr.replace(/\+/g, " ").replace(/:[^:]+/g, "");

// Generate CSS content
let cssContent = `/**
 * Auto-generated from theme.json
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: node scripts/generateThemeCSS.js
 */

@theme {
  /* === Colors === */\n`;

// Default colors
Object.entries(themeConfig.colors.default.theme_color).forEach(
  ([key, value]) => {
    cssContent += `  --color-${toKebab(key)}: ${value};\n`;
  },
);

Object.entries(themeConfig.colors.default.text_color).forEach(
  ([key, value]) => {
    cssContent += `  --color-${toKebab(key)}: ${value};\n`;
  },
);

// Darkmode colors (prefixed)
if (themeConfig.colors.darkmode) {
  cssContent += `\n  /* Darkmode colors */\n`;
  Object.entries(themeConfig.colors.darkmode.theme_color).forEach(
    ([key, value]) => {
      cssContent += `  --color-darkmode-${toKebab(key)}: ${value};\n`;
    },
  );

  Object.entries(themeConfig.colors.darkmode.text_color).forEach(
    ([key, value]) => {
      cssContent += `  --color-darkmode-${toKebab(key)}: ${value};\n`;
    },
  );
}

// Font families
cssContent += `\n  /* === Font Families === */\n`;
Object.entries(themeConfig.fonts.font_family)
  .filter(([key]) => !key.includes("type"))
  .forEach(([key, font]) => {
    const fontFamily = `${findFont(font)}, ${themeConfig.fonts.font_family[`${key}_type`] || "sans-serif"}`;
    cssContent += `  --font-${toKebab(key)}: ${fontFamily};\n`;
  });

// Font sizes
const baseSize = Number(themeConfig.fonts.font_size.base);
const scale = Number(themeConfig.fonts.font_size.scale);

cssContent += `\n  /* === Font Sizes === */\n`;
cssContent += `  --text-base: ${baseSize}px;\n`;
cssContent += `  --text-base-sm: ${baseSize * 0.8}px;\n`;

let currentSize = scale;
for (let i = 6; i >= 1; i--) {
  cssContent += `  --text-h${i}: ${currentSize}rem;\n`;
  cssContent += `  --text-h${i}-sm: ${currentSize * 0.9}rem;\n`;
  currentSize *= scale;
}

cssContent += `}\n`;

// Write the file
fs.writeFileSync(outputPath, cssContent);
console.log("✅ Theme CSS generated successfully at:", outputPath);
